version: 2
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable
instructions:
  Build:
    - !include "{{qt-labs/qtquickdesigner-components}}/common_settings.yaml"
  Test: []  # To be enabled
